export const predefinedChallenges = [
    // { id: "1", name: "No Coffee for a Week", goal: 7, badgeReward: "☕🚫 Caffeine-Free Champ", points: 70 },
    // { id: "2", name: "Save ₹100 Every Day", goal: 30, badgeReward: "🏆 Savings Champion!", points: 300 },
    // { id: "3", name: "Cancel One Subscription", goal: 1, badgeReward: "💡 Smart Saver", points: 100 },
    {
      id: "1",
      title: "Save ₹500 this month",
      description: "Deposit at least ₹500 into your savings account this month",
      icon: "IndianRupee",
      points: 1000,
      progress: 0,
      total: 500,
      daysLeft: 30,
      difficulty: "medium",
      category: "savings",
    },
    {
      id: "2",
      title: "Complete financial profile",
      description: "Fill out all sections of your financial profile",
      icon: "Target",
      points: 500,
      progress: 0,
      total: 100,
      daysLeft: 30,
      difficulty: "easy",
      category: "savings",
    },
    {
      id: "3",
      title: "Invest in 3 different assets",
      description:
        "Diversify your portfolio by investing in 3 different asset types",
      icon: "Percent",
      points: 1500,
      progress: 0,
      total: 3,
      daysLeft: 30,
      difficulty: "hard",
      category: "investing",
    },
    {
      id: "4",
      title: "No unnecessary purchases for a week",
      description:
        "Avoid making any non-essential purchases for 7 consecutive days",
      icon: "ShoppingBag",
      points: 750,
      progress: 0,
      total: 7,
      daysLeft: 7,
      difficulty: "medium",
      category: "spending",
    },
    {
      id: "5",
      title: "Set up automatic savings",
      description: "Configure automatic transfers to your savings account",
      icon: "Zap",
      points: 600,
      progress: 0,
      total: 100,
      daysLeft: 30,
      difficulty: "easy",
      category: "savings",
    },
    {
      id: "6",
      title: "Refer a friend",
      description: "Invite a friend to join the platform",
      icon: "Award",
      points: 1000,
      progress: 0,
      total: 1,
      daysLeft: 30,
      difficulty: "easy",
      category: "savings",
    },
  ];
  