export const predefinedRewards = [
    {
      id: "1",
      title: "₹250 Amazon Gift Card",
      description: "Redeem your points for an Amazon gift card",
      pointsCost: 2500,
      image: "/amazon-gift-card.png",
      category: "gift-card",
      brand: "Amazon",
      featured: true,
    },
    {
      id: "2",
      title: "₹100 Target Gift Card",
      description: "Redeem your points for a Target gift card",
      pointsCost: 5000,
      image: "/100-target-gift-card.png",
      category: "gift-card",
      brand: "Target",
    },
    {
      id: "3",
      title: "₹150 Starbucks Gift Card",
      description: "Redeem your points for a Starbucks gift card",
      pointsCost: 1500,
      image: "/starbucks-gift-card.png",
      category: "gift-card",
      brand: "Starbucks",
    },
    {
      id: "4",
      title: "5% Cashback Boost",
      description: "Get an extra 5% cashback on all purchases for a month",
      pointsCost: 3000,
      image: "/5-percent-cashback-gift-card.png",
      category: "cashback",
    },
    {
      id: "5",
      title: "Premium Subscription (1 Month)",
      description: "Upgrade to premium features for one month",
      pointsCost: 2000,
      image: "/membership-card.png",
      category: "experience",
      featured: true,
    },
    {
      id: "6",
      title: "10% Off Next Investment Fee",
      description: "Get 10% off your next investment transaction fee",
      pointsCost: 1500,
      image: "/10-percent-off-investment-fee.png",
      category: "discount",
    },
    {
      id: "7",
      title: "₹150 Uber Gift Card",
      description: "Redeem your points for an Uber ride",
      pointsCost: 1500,
      image: "/uber-gift-card.png",
      category: "gift-card",
      brand: "Uber",
    },
    {
      id: "8",
      title: "Financial Planning Session",
      description: "One-on-one session with a financial advisor",
      pointsCost: 7500,
      image: "/financial-planning-session.png",
      category: "experience",
    },
  ];