export const predefinedChallenges = [
    {
      id: "ch-001",
      title: "Save ₹500 this month",
      description: "Deposit at least ₹500 into your savings account this month",
      completationText: "Successfully saved ₹500 in your savings account",
      icon: "IndianRupee",
      points: 1000,
      progress: 0,
      total: 500,
      daysLeft: 30,
      difficulty: "medium",
      category: "savings",
    },
    {
      id: "ch-002",
      title: "Complete financial profile",
      description: "Fill out all sections of your financial profile",
      completationText: "Successfully completed your financial profile",
      icon: "Target",
      points: 500,
      progress: 0,
      total: 100,
      daysLeft: 30,
      difficulty: "easy",
      category: "savings",
    },
    {
      id: "ch-003",
      title: "Invest in 3 different assets",
      description:
        "Diversify your portfolio by investing in 3 different asset types",
      completationText: "Successfully invested in 3 different assets",
      icon: "Percent",
      points: 1500,
      progress: 0,
      total: 3,
      daysLeft: 30,
      difficulty: "hard",
      category: "investing",
    },
    {
      id: "ch-004",
      title: "No unnecessary purchases for a week",
      description:
        "Avoid making any non-essential purchases for 7 consecutive days",
      completationText: "Successfully avoided unnecessary purchases for a week",
      icon: "ShoppingBag",
      points: 750,
      progress: 0,
      total: 7,
      daysLeft: 7,
      difficulty: "medium",
      category: "spending",
    },
    {
      id: "ch-006",
      title: "Set up automatic savings",
      description: "Configure automatic transfers to your savings account",
      completationText: "Successfully set up automatic savings transfers",
      icon: "Zap",
      points: 600,
      progress: 0,
      total: 100,
      daysLeft: 30,
      difficulty: "easy",
      category: "savings",
    },
    {
      id: "ch-007",
      title: "Refer a friend",
      description: "Invite a friend to join the platform",
      completationText: "Your friend signed up using your referral link",
      icon: "Award",
      points: 1000,
      progress: 0,
      total: 1,
      daysLeft: 30,
      difficulty: "easy",
      category: "savings",
    },
  ];
  