export const predefinedRewards = [
    {
      id: "rwd-001",
      title: "₹250 Amazon Gift Card",
      description: "Redeem your points for an Amazon gift card",
      completationText: "Gift card will be sent to your email",
      pointsCost: 2500,
      image: "/amazon-gift-card.png",
      icon: "Gift",
      category: "gift-card",
      brand: "Amazon",
      featured: true,
    },
    {
      id: "rwd-002",
      title: "₹100 Target Gift Card",
      description: "Redeem your points for a Target gift card",
      completationText: "Gift card will be sent to your email",
      pointsCost: 5000,
      image: "/100-target-gift-card.png",
      icon: "Gift",
      category: "gift-card",
      brand: "Target",
    },
    {
      id: "rwd-003",
      title: "₹150 Starbucks Gift Card",
      description: "Redeem your points for a Starbucks gift card",
      completationText: "Gift card will be sent to your email",
      pointsCost: 1500,
      image: "/starbucks-gift-card.png",
      icon: "Gift",
      category: "gift-card",
      brand: "Starbucks",
    },
    {
      id: "rwd-004",
      title: "5% Cashback Boost",
      description: "Get an extra 5% cashback on all purchases for a month",
      completationText: "%% cashback boost will be applied to your account",
      pointsCost: 3000,
      image: "/5-percent-cashback-gift-card.png",
      icon: "TrendingUp",
      category: "cashback",
    },
    {
      id: "rwd-005",
      title: "Premium Subscription (1 Month)",
      description: "Upgrade to premium features for one month",
      completationText: "Premium subscription activated for 1 month",
      pointsCost: 2000,
      image: "/membership-card.png",
      icon: "Star",
      category: "experience",
      featured: true,
    },
    {
      id: "rwd-006",
      title: "10% Off Next Investment Fee",
      description: "Get 10% off your next investment transaction fee",
      completationText: "10% off will be applied to your next investment fee",
      pointsCost: 1500,
      image: "/10-percent-off-investment-fee.png",
      icon: "Percent",
      category: "discount",
    },
    {
      id: "rwd-007",
      title: "₹150 Uber Gift Card",
      description: "Redeem your points for an Uber ride",
      completationText: "Gift card will be sent to your email",
      pointsCost: 1500,
      image: "/uber-gift-card.png",
      icon: "Gift",
      category: "gift-card",
      brand: "Uber",
    },
    {
      id: "rwd-008",
      title: "Financial Planning Session",
      description: "One-on-one session with a financial advisor",
      completationText: "Financial planning session booked. Details will be sent to your email",
      pointsCost: 7500,
      image: "/financial-planning-session.png",
      icon: "UserCheck",
      category: "experience",
    },
  ];